
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ENTERO IDENTIFICADOR OPERADOR PRIORIDAD SIMBOLO\n    expresion : nombre fecha genero estado\n    \n    nombre : PRIORIDAD IDENTIFICADOR IDENTIFICADOR IDENTIFICADOR\n           | PRIORIDAD IDENTIFICADOR IDENTIFICADOR IDENTIFICADOR IDENTIFICADOR\n    \n    fecha : PRIORIDAD ENTERO ENTERO ENTERO\n    \n    genero : PRIORIDAD IDENTIFICADOR\n    \n    estado : PRIORIDAD IDENTIFICADOR\n    '
    
_lr_action_items = {'PRIORIDAD':([0,2,4,7,13,15,17,18,],[3,5,8,12,-5,-2,-4,-3,]),'$end':([1,11,16,],[0,-1,-6,]),'IDENTIFICADOR':([3,6,8,10,12,15,],[6,10,13,15,16,18,]),'ENTERO':([5,9,14,],[9,14,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),'nombre':([0,],[2,]),'fecha':([2,],[4,]),'genero':([4,],[7,]),'estado':([7,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> nombre fecha genero estado','expresion',4,'p_CURP','Analizador_sintactico.py',16),
  ('nombre -> PRIORIDAD IDENTIFICADOR IDENTIFICADOR IDENTIFICADOR','nombre',4,'p_nombre','Analizador_sintactico.py',65),
  ('nombre -> PRIORIDAD IDENTIFICADOR IDENTIFICADOR IDENTIFICADOR IDENTIFICADOR','nombre',5,'p_nombre','Analizador_sintactico.py',66),
  ('fecha -> PRIORIDAD ENTERO ENTERO ENTERO','fecha',4,'p_fecha','Analizador_sintactico.py',201),
  ('genero -> PRIORIDAD IDENTIFICADOR','genero',2,'p_genero','Analizador_sintactico.py',230),
  ('estado -> PRIORIDAD IDENTIFICADOR','estado',2,'p_estado','Analizador_sintactico.py',248),
]
